name: Recordingtoggle
version: '${project.version}'
main: com.green.recordingtoggle.recordingtoggle.Recordingtoggle
api-version: 1.18
authors: [ Green ]
description: Toggle a recording status in-game!
depend:
  - Essentials
commands:
  Recording:
    description: Toggles recording status
    usage: /<command>

